//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeTurnos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemaDeTurnosEntities : DbContext
    {
        public SystemaDeTurnosEntities()
            : base("name=SystemaDeTurnosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ficha> Ficha { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Observacion> Observacion { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Tratamiento> Tratamiento { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
    }
}
